### ISSUE TITLE
To do - 26/04/2024

### ISSUE THREAD

**Issue by charlenefialho** [laiscrz/CP2-IA#3]
Realizar gráficos dos atributos abaixos, para analisar qual tem menos discrepância e definir o peso de cada um, para realizar definir o score de resultado e com o score definirmos os grupos de tamanho de empresa.

- Faturamento Bruto 

- Margem Bruta 

- Ativo Total 

Realizar a montagem  do modelo de classificação, para a definição(status, definição risco e percentual risco).

**Comment by laiscrz** [comment]
Gráfico de matriz de correlação para analisar a 'discrepância' => ok
definição de peso => ok
Score de definição de grupos de tamanho empresa => ok
Modelo => ok
